# Generated by Django 4.2.6 on 2023-11-21 01:34

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.CharField(default=api.user.models.getHostURL, max_length=255),
        ),
    ]
