# Generated by Django 4.2.6 on 2023-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_user_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
